/**
 * The per-session policy that says what a confined agent may touch.
 *
 * Kept apart from the backend that runs it, because this is the whole of the
 * containment guarantee and it is worth being able to read, test, and diff on
 * its own. Everything here is a name or a path; no secret is ever written into
 * a policy.
 */

import { join } from "@std/path";
import type { NetworkMode, PolicyExtraConfig } from "../config/schema.ts";
import {
  AGENT_BIN,
  AGENT_HOME,
  type SandboxLaunch,
  STATE_PATH,
  WORKSPACE_PATH,
} from "./backend.ts";
import { type AgentRuntime, SANDBOX_PATH } from "./runtime.ts";

/** The bundled profile for a coding agent: its project and outbound HTTPS. */
export const AGENT_PROFILE = "ai-agent";

/** The profile used when a session is given no network at all. */
export const OFFLINE_PROFILE = "untrusted";

/** Where a session's policy file is written, inside its state directory. */
export const POLICY_FILENAME = "policy.toml";

/** Filename of the resolver a session is given, in the daemon's state root. */
export const RESOLV_FILENAME = "resolv.conf";

/**
 * What a session may read outside its own directories.
 *
 * Named rather than inherited, so what a session can reach is bounded by this
 * list rather than by whatever else happens to live on the host. With exactly
 * this, the agent, git, python with TLS, and ripgrep run, and the agent reaches
 * its provider over HTTPS. `/sys` is not needed at all.
 */
const SYSTEM_READ = [
  // Programs, libraries, and their data.
  "/usr",
  "/lib",
  "/lib64",
  "/bin",
  "/sbin",
  // Its own processes. A fresh procfs in the session's PID namespace.
  "/proc",
  // What the dynamic linker reads to find a library. Without this, nothing
  // dynamically linked starts at all.
  "/etc/ld.so.cache",
  "/etc/ld.so.conf",
  "/etc/ld.so.conf.d",
  // Certificate authorities, or TLS fails and the provider is unreachable.
  "/etc/ssl",
  "/etc/ca-certificates.conf",
  "/etc/pki",
  // Name resolution. The resolver itself is not from here: see RESOLV_CONF.
  "/etc/nsswitch.conf",
  // Static tables a networking tool expects to find. They name no host.
  "/etc/services",
  "/etc/protocols",
];

/** Where the agent may run programs from. */
const SYSTEM_EXECUTE = ["/usr", "/lib", "/lib64", "/bin", "/sbin"];

/**
 * The resolver a session is given, in place of the host's.
 *
 * The host's `/etc/resolv.conf` names whoever resolves for this machine, which
 * on a home network is the ISP and on a private one is the network itself. A
 * session has no use for that and cannot be stopped from repeating it, so it
 * is given a public resolver instead. Queries still leave over the host's
 * connection, so this hides which resolver the operator uses rather than the
 * fact that a lookup happened.
 *
 * One file for the daemon rather than one per session: the contents are the
 * same for every session, and a copy inside a session's own state directory
 * would sit under a grant that is placed elsewhere and never be bound.
 */
export const RESOLV_CONF = [
  "# Generated by errand. The host's own resolver is not shown to a session.",
  "nameserver 1.1.1.1",
  "nameserver 1.0.0.1",
  "options edns0",
].join("\n");

/** Renders one TOML string. Names only, so no secret is ever written here. */
function quoted(name: string): string {
  return JSON.stringify(name);
}

/** A host path bound where the agent expects to find it. */
function placed(host: string, at: string): string {
  return `{ path = ${quoted(host)}, at = ${quoted(at)} }`;
}

/** Where a session's policy file lives. Never inside the project. */
export function policyPath(launch: SandboxLaunch): string {
  return join(launch.stateDir, POLICY_FILENAME);
}

/**
 * Builds the per-session policy.
 *
 * It is written into the session's state directory, never into the project.
 * The agent can write to its project, so a policy living there would be a
 * policy the agent could rewrite, which is not a policy.
 *
 * `resolvConf` is required rather than defaulted: a caller that forgot it
 * would silently hand the session the host's own resolver.
 */
export function policyContents(options: {
  launch: SandboxLaunch;
  network: NetworkMode;
  /** Ports a session may open outbound. Empty falls back to HTTPS alone. */
  egressPorts?: number[] | undefined;
  runtime: AgentRuntime;
  fileMax: string;
  resolvConf: string;
  /**
   * Paths the operator granted on top of these.
   *
   * Appended, never substituted: what is generated above is the floor, and
   * this can only widen it. A session that needs a shared toolchain or a
   * package cache is the case this exists for.
   */
  extra?: PolicyExtraConfig | undefined;
  /**
   * Variables the operator set, for a toolchain that reads one.
   *
   * A name the daemon already passes is left alone: the credential and the
   * GitHub token are plumbing rather than settings, and a policy that let a
   * file shadow either would decide what the agent authenticates as.
   */
  env?: Record<string, string> | undefined;
  /** Directories the operator added to the session's PATH. */
  pathExtra?: string[] | undefined;
}): string {
  const { launch, network, runtime, fileMax, resolvConf } = options;
  const extra = options.extra ?? { read: [], write: [], execute: [] };
  const operatorEnv = Object.entries(options.env ?? {})
    .filter(([name]) => launch.env[name] === undefined);

  // The project and the session state are placed at fixed paths, so the agent
  // sees the same two under any backend and never a host path.
  //
  // The state directory is readable as well as writable. A grant of write does
  // not imply read, and the agent reads back everything it keeps there: its
  // credential store, the system prompt the daemon writes for it, and the
  // history a resumed thread continues from.
  const read = [
    ...SYSTEM_READ.map(quoted),
    placed(resolvConf, "/etc/resolv.conf"),
    placed(launch.projectPath, WORKSPACE_PATH),
    placed(launch.stateDir, STATE_PATH),
    // The agent's own program stays where it is installed. An interpreter
    // resolves its modules relative to itself, so moving it breaks it.
    ...runtime.readPaths.map(quoted),
    ...extra.read.map(quoted),
  ];

  // Ahead of everything, so a wrapper stands in for the program it names.
  // The operator's own directories sit ahead of the system ones: a toolchain
  // named on purpose is the one a session should find, not the host's copy.
  const path = [AGENT_BIN, ...runtime.pathEntries, ...(options.pathExtra ?? []), ...SANDBOX_PATH];

  const lines = [
    "# Generated per session by errand. Do not edit.",
    "[filesystem]",
    // Clears the profile's grants, so the list below is the whole of what a
    // session can reach rather than an addition to a wider floor.
    "reset = true",
    `read = [${read.join(", ")}]`,
    `write = [${
      [
        placed(launch.projectPath, WORKSPACE_PATH),
        placed(launch.stateDir, STATE_PATH),
        ...extra.write.map(quoted),
      ].join(", ")
    }]`,
    `execute = [${[...SYSTEM_EXECUTE, AGENT_BIN, ...extra.execute].map(quoted).join(", ")}]`,
    "",
    "[env]",
    // The environment is built rather than inherited, so a variable not named
    // here does not cross. The provider credential is named and nothing else
    // is: the daemon's own environment holds the chat token, and this is the
    // boundary that keeps it out of a session.
    `pass = [${Object.keys(launch.env).sort().map(quoted).join(", ")}]`,
    // HOME is set here rather than on the sandbox process. The tool derives its
    // own world from the caller's HOME, so pointing that at a placed path makes
    // it try to create the path on the host, which fails. Set in the policy, it
    // reaches the target after the pivot, where the path exists.
    `set = { ${
      [
        `PATH = ${quoted(path.join(":"))}`,
        `HOME = ${quoted(AGENT_HOME)}`,
        ...operatorEnv.map(([name, value]) => `${name} = ${quoted(value)}`),
      ].join(", ")
    } }`,
    "",
    // An rlimit rather than a cgroup control, so it holds on a host with no
    // delegated cgroup, which is the case this backend most often runs on.
    "[resources]",
    `file_max = ${quoted(fileMax)}`,
  ];

  if (network !== "none") {
    const openPorts = options.egressPorts?.length ? options.egressPorts : [443];
    const allow = openPorts.map((port) => `{ host = "*", port = ${port} }`).join(", ");
    lines.push("", "[network]", `egress_allow = [${allow}]`);
  }
  return `${lines.join("\n")}\n`;
}
